//
// AUTOGENERATED 12/30/2008 4:01:14 PM
//
using System;

namespace Stream
{
	public abstract class Evaluator
	{

		public Evaluator()
		{
		}

		public object Evaluate(Node node)
		{
			switch (node.Type)
			{
				case NodeType.Expression:
					{
						if(node.Nodes.Count == 1 && node.Nodes[0].Type == NodeType.BOOLEAN)
						{
							return EvaluateBOOLEAN(node.Nodes[0].Value);
						}
						if(node.Nodes.Count == 1 && node.Nodes[0].Type == NodeType.INTEGER)
						{
							return EvaluateINTEGER(node.Nodes[0].Value);
						}
						if(node.Nodes.Count == 1 && node.Nodes[0].Type == NodeType.FLOAT)
						{
							return EvaluateFLOAT(node.Nodes[0].Value);
						}
						if(node.Nodes.Count == 1 && node.Nodes[0].Type == NodeType.CHARACTER)
						{
							return EvaluateCHARACTER(node.Nodes[0].Value);
						}
						if(node.Nodes.Count == 1 && node.Nodes[0].Type == NodeType.STRING)
						{
							return EvaluateSTRING(node.Nodes[0].Value);
						}
						if(node.Nodes.Count == 2 && node.Nodes[0].Type == NodeType.IDENTIFIER && node.Nodes[1].Type == NodeType.ExpressionTail)
						{
							return EvaluateIDENTIFIERExpressionTail(node);
						}
						throw new System.Exception("Invalid expression.");
					}
				case NodeType.ExpressionList:
					{
						if(node.Nodes.Count == 2 && node.Nodes[0].Type == NodeType.Expression && node.Nodes[1].Type == NodeType.ExpressionListTail)
						{
							return EvaluateExpressionExpressionListTail(node);
						}
						throw new System.Exception("Invalid expression.");
					}
				case NodeType.ExpressionListTail:
					{
						if(node.Nodes.Count == 3 && node.Nodes[0].Type == NodeType.COMMA && node.Nodes[1].Type == NodeType.Expression && node.Nodes[2].Type == NodeType.ExpressionListTail)
						{
							return EvaluateCOMMAExpressionExpressionListTail(node);
						}
						throw new System.Exception("Invalid expression.");
					}
				case NodeType.ExpressionTail:
					{
						if(node.Nodes.Count == 2 && node.Nodes[0].Type == NodeType.ASSIGNMENT && node.Nodes[1].Type == NodeType.Expression)
						{
							return EvaluateASSIGNMENTExpression(node);
						}
						if(node.Nodes.Count == 2 && node.Nodes[0].Type == NodeType.EQUALS && node.Nodes[1].Type == NodeType.Expression)
						{
							return EvaluateEQUALSExpression(node);
						}
						if(node.Nodes.Count == 3 && node.Nodes[0].Type == NodeType.LEFT_PAREN && node.Nodes[1].Type == NodeType.ExpressionList && node.Nodes[2].Type == NodeType.RIGHT_PAREN)
						{
							return EvaluateLEFT_PARENExpressionListRIGHT_PAREN(node);
						}
						throw new System.Exception("Invalid expression.");
					}
				case NodeType.ASSIGNMENT:
					{
						return EvaluateASSIGNMENT(node.Value);
					}
				case NodeType.BOOLEAN:
					{
						return EvaluateBOOLEAN(node.Value);
					}
				case NodeType.CHARACTER:
					{
						return EvaluateCHARACTER(node.Value);
					}
				case NodeType.COMMA:
					{
						return EvaluateCOMMA(node.Value);
					}
				case NodeType.EQUALS:
					{
						return EvaluateEQUALS(node.Value);
					}
				case NodeType.FLOAT:
					{
						return EvaluateFLOAT(node.Value);
					}
				case NodeType.IDENTIFIER:
					{
						return EvaluateIDENTIFIER(node.Value);
					}
				case NodeType.INTEGER:
					{
						return EvaluateINTEGER(node.Value);
					}
				case NodeType.LEFT_PAREN:
					{
						return EvaluateLEFT_PAREN(node.Value);
					}
				case NodeType.RIGHT_PAREN:
					{
						return EvaluateRIGHT_PAREN(node.Value);
					}
				case NodeType.STRING:
					{
						return EvaluateSTRING(node.Value);
					}
				default:
					{
						throw new System.Exception("Invalid expression.");
					}
			}
		}

		protected virtual object EvaluateBOOLEAN(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateINTEGER(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateFLOAT(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateCHARACTER(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateSTRING(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateIDENTIFIERExpressionTail(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateExpressionExpressionListTail(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateCOMMAExpressionExpressionListTail(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateASSIGNMENTExpression(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateEQUALSExpression(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateLEFT_PARENExpressionListRIGHT_PAREN(Node node)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateASSIGNMENT(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateCOMMA(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateEQUALS(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateIDENTIFIER(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateLEFT_PAREN(string value)
		{
			throw new System.Exception("Implement.");
		}

		protected virtual object EvaluateRIGHT_PAREN(string value)
		{
			throw new System.Exception("Implement.");
		}

	}
}
