//
// AUTOGENERATED 12/30/2008 4:01:14 PM
//
using System;

namespace Stream
{
	public class NodeType
	{
		// Nonterminals
		public const int Expression = 0;
		public const int ExpressionList = 1;
		public const int ExpressionListTail = 2;
		public const int ExpressionTail = 3;

		// Terminals
		public const int ASSIGNMENT = 4;
		public const int BOOLEAN = 5;
		public const int CHARACTER = 6;
		public const int COMMA = 7;
		public const int EPSILON = 8;
		public const int EQUALS = 9;
		public const int FLOAT = 10;
		public const int IDENTIFIER = 11;
		public const int INTEGER = 12;
		public const int LEFT_PAREN = 13;
		public const int RIGHT_PAREN = 14;
		public const int STRING = 15;

	}
}
