//
// AUTOGENERATED 12/30/2008 4:01:13 PM
//
using System;

namespace Stream
{
	public class Token
	{
		public int Type;
		public string Value;

		public Token(int type)
		{
			Type = type;
			Value = null;
		}

		public Token(int type, string value)
		{
			Type = type;
			Value = value;
		}

	}
}
