//
// AUTOGENERATED 12/30/2008 4:01:13 PM
//
using System;

namespace Stream
{
	public class TokenType
	{
		public const int STRING = 0;
		public const int CHARACTER = 1;
		public const int LEFT_PAREN = 2;
		public const int RIGHT_PAREN = 3;
		public const int COMMA = 4;
		public const int INTEGER = 5;
		public const int FLOAT = 6;
		public const int ASSIGNMENT = 7;
		public const int EQUALS = 8;
		public const int IDENTIFIER = 9;
		public const int BOOLEAN = 10;

		public const int _ERROR_ = 11;
		public const int _EOF_ = 12;
	}
}
