//
// AUTOGENERATED 4/15/2009 8:21:57 PM
//
using System;

namespace Bamboo.Html
{
	public class HtmlNodeType
	{
		// Nonterminals
		public const int Attribute = 0;
		public const int AttributeList = 1;
		public const int AttributeTail = 2;
		public const int AttributeTail2 = 3;
		public const int Content = 4;
		public const int EndTag = 5;
		public const int Node = 6;
		public const int StartTag = 7;

		// Terminals
		public const int EPSILON = 8;
		public const int EQUALS = 9;
		public const int FLOAT = 10;
		public const int GREATER_THAN = 11;
		public const int INTEGER = 12;
		public const int LESS_THAN = 13;
		public const int LESS_THAN_FORWARD_SLASH = 14;
		public const int QUOTED_STRING = 15;
		public const int STRING = 16;

	}
}
