//
// AUTOGENERATED 3/2/2009 1:21:50 PM
//
using System;

namespace Bamboo.Html
{
	public class HtmlTokenType
	{
		public const int QUOTED_STRING = 0;
		public const int LESS_THAN = 1;
		public const int LESS_THAN_FORWARD_SLASH = 2;
		public const int GREATER_THAN = 3;
		public const int EQUALS = 4;
		public const int STRING = 5;
		public const int FORWARD_SLASH = 6;
		public const int INTEGER = 7;
		public const int FLOAT = 8;

		public const int _ERROR_ = 9;
		public const int _EOF_ = 10;
	}
}
