//
// AUTOGENERATED 3/2/2009 1:21:50 PM
//
using System;

namespace Bamboo.Html
{
	public class HtmlToken
	{
		public int Type;
		public string Value;

		public HtmlToken(int type)
		{
			Type = type;
			Value = null;
		}

		public HtmlToken(int type, string value)
		{
			Type = type;
			Value = value;
		}

	}
}
