//
// AUTOGENERATED 2/26/2009 12:33:14 PM
//
using System;

namespace Bamboo.Css
{
	public class CssNodeType
	{
		// Nonterminals
		public const int Declaration = 0;
		public const int DeclarationList = 1;
		public const int Rule = 2;
		public const int RuleList = 3;
		public const int Selector = 4;
		public const int SelectorTail = 5;
		public const int Value = 6;
		public const int ValueList = 7;

		// Terminals
		public const int BOOLEAN = 8;
		public const int COLON = 9;
		public const int EPSILON = 10;
		public const int EQUALS = 11;
		public const int FLOAT = 12;
		public const int IDENTIFIER = 13;
		public const int INTEGER = 14;
		public const int LEFT_BRACKET = 15;
		public const int LEFT_CURLY_BRACE = 16;
		public const int RIGHT_BRACKET = 17;
		public const int RIGHT_CURLY_BRACE = 18;
		public const int SEMICOLON = 19;
		public const int STRING = 20;

	}
}
