//
// AUTOGENERATED 2/26/2009 12:33:14 PM
//
using System;

namespace Bamboo.Css
{
	public class CssTokenType
	{
		public const int LEFT_CURLY_BRACE = 0;
		public const int RIGHT_CURLY_BRACE = 1;
		public const int COLON = 2;
		public const int SEMICOLON = 3;
		public const int LEFT_BRACKET = 4;
		public const int RIGHT_BRACKET = 5;
		public const int EQUALS = 6;
		public const int STRING = 7;
		public const int INTEGER = 8;
		public const int FLOAT = 9;
		public const int IDENTIFIER = 10;
		public const int BOOLEAN = 11;

		public const int _ERROR_ = 12;
		public const int _EOF_ = 13;
	}
}
