//
// AUTOGENERATED 2/26/2009 12:33:14 PM
//
using System;

namespace Bamboo.Css
{
	public class CssTokenizer
	{
		private System.Text.StringBuilder _stringBuilder = new System.Text.StringBuilder();

		public CssTokenizer()
		{
		}

		public CssToken Tokenize(CssTextReader reader)
		{
			int n;
			char ch;

			_stringBuilder.Length = 0;

			//
			// Trim whitespace
			//
			while ((n = reader.Peek()) != -1)
			{
				ch = (char)n;
				switch (ch)
				{
					case ' ':
					case '\t':
					case '\r':
					case '\n':
						{
							reader.Read();
							break;
						}
					default:
						{
							goto s0;
						}
				}
			}

		s0:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '{':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s1;
					}
				case '}':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s2;
					}
				case ':':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s3;
					}
				case ';':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s4;
					}
				case '[':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s5;
					}
				case ']':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s6;
					}
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s7;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s8;
					}
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s11;
					}
				case 't':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'f':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s19;
					}
				case '0':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s22;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s1:
			return new CssToken(CssTokenType.LEFT_CURLY_BRACE, _stringBuilder.ToString());

		s2:
			return new CssToken(CssTokenType.RIGHT_CURLY_BRACE, _stringBuilder.ToString());

		s3:
			return new CssToken(CssTokenType.COLON, _stringBuilder.ToString());

		s4:
			return new CssToken(CssTokenType.SEMICOLON, _stringBuilder.ToString());

		s5:
			return new CssToken(CssTokenType.LEFT_BRACKET, _stringBuilder.ToString());

		s6:
			return new CssToken(CssTokenType.RIGHT_BRACKET, _stringBuilder.ToString());

		s7:
			return new CssToken(CssTokenType.EQUALS, _stringBuilder.ToString());

		s8:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case ' ':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s9;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s9:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case ' ':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s9;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s10;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s10:
			return new CssToken(CssTokenType.STRING, _stringBuilder.ToString());

		s11:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.INTEGER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s11;
					}
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s12;
					}
				default:
					{
						return new CssToken(CssTokenType.INTEGER, _stringBuilder.ToString());
					}
			}

		s12:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s13;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s13:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.FLOAT, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s13;
					}
				default:
					{
						return new CssToken(CssTokenType.FLOAT, _stringBuilder.ToString());
					}
			}

		s14:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'r':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s16;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s15:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s16:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'u':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s17;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s17:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'e':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s18;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s18:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.BOOLEAN, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				default:
					{
						return new CssToken(CssTokenType.BOOLEAN, _stringBuilder.ToString());
					}
			}

		s19:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'a':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s20;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s20:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 'l':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s21;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s21:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 's':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s17;
					}
				default:
					{
						return new CssToken(CssTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s22:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CssToken(CssTokenType._EOF_);
				}
				else
				{
					return new CssToken(CssTokenType.INTEGER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s12;
					}
				default:
					{
						return new CssToken(CssTokenType.INTEGER, _stringBuilder.ToString());
					}
			}

		se:
			return new CssToken(CssTokenType._ERROR_, _stringBuilder.ToString());

		}

	}
}
