//
// AUTOGENERATED 7/19/2009 5:57:00 PM
//
using System;

namespace Bamboo.Sql2
{
	public class SqlNodeType
	{
		// Nonterminals
		public const int AscDesc = 0;
		public const int ColumnList = 1;
		public const int ColumnListTail = 2;
		public const int ComparisonOperator = 3;
		public const int From = 4;
		public const int FunctionParameterList = 5;
		public const int FunctionParameterListTail = 6;
		public const int GroupByClause = 7;
		public const int GroupByTail = 8;
		public const int JoinList = 9;
		public const int LogicalOperator = 10;
		public const int OrderByClause = 11;
		public const int OrderByTail = 12;
		public const int Predicate = 13;
		public const int PredicateIdentifierTail = 14;
		public const int PredicateTail = 15;
		public const int Select = 16;
		public const int SelectItem = 17;
		public const int SelectItemAlias = 18;
		public const int SelectItemTail = 19;
		public const int SelectList = 20;
		public const int SelectListTail = 21;
		public const int SetList = 22;
		public const int SetListTail = 23;
		public const int Statement = 24;
		public const int StatementTail = 25;
		public const int TableList = 26;
		public const int TableListTail = 27;
		public const int TableTail = 28;
		public const int Union = 29;
		public const int VALUE = 30;
		public const int ValueList = 31;
		public const int ValueListTail = 32;
		public const int WhereClause = 33;

		// Terminals
		public const int AND = 34;
		public const int AS = 35;
		public const int ASC = 36;
		public const int BETWEEN = 37;
		public const int BY = 38;
		public const int COMMA = 39;
		public const int DATE = 40;
		public const int DELETE = 41;
		public const int DESC = 42;
		public const int EPSILON = 43;
		public const int EQUALS = 44;
		public const int FLOAT = 45;
		public const int FROM = 46;
		public const int GREATER_THAN = 47;
		public const int GREATER_THAN_OR_EQUAL = 48;
		public const int GROUP = 49;
		public const int IDENTIFIER = 50;
		public const int INNER = 51;
		public const int INSERT = 52;
		public const int INTEGER = 53;
		public const int INTO = 54;
		public const int JOIN = 55;
		public const int LEFT = 56;
		public const int LEFT_PAREN = 57;
		public const int LESS_THAN = 58;
		public const int LESS_THAN_OR_EQUAL = 59;
		public const int LIKE = 60;
		public const int NOT = 61;
		public const int NOT_EQUALS = 62;
		public const int ON = 63;
		public const int OR = 64;
		public const int ORDER = 65;
		public const int OUTER = 66;
		public const int QUOTED_STRING = 67;
		public const int REPLACE = 68;
		public const int RIGHT = 69;
		public const int RIGHT_PAREN = 70;
		public const int SELECT = 71;
		public const int SEMICOLON = 72;
		public const int SET = 73;
		public const int UNION = 74;
		public const int UPDATE = 75;
		public const int VALUES = 76;
		public const int WHERE = 77;

	}
}
