//
// AUTOGENERATED 7/19/2009 5:56:59 PM
//
using System;

namespace Bamboo.Sql2
{
	public class SqlToken
	{
		public int Type;
		public string Value;

		public SqlToken(int type)
		{
			Type = type;
			Value = null;
		}

		public SqlToken(int type, string value)
		{
			Type = type;
			Value = value;
		}

	}
}
