//
// AUTOGENERATED 7/19/2009 5:56:59 PM
//
using System;

namespace Bamboo.Sql2
{
	public class SqlTextReader
	{
		private System.IO.TextReader _reader;

		public int Line = 1;
		public int Column = 1;

		public SqlTextReader(System.IO.TextReader reader)
		{
			this._reader = reader;
		}

		public int Peek()
		{
			return this._reader.Peek();
		}

		public int Read()
		{
			char ch = (char)this._reader.Read();
			if(ch == '\n')
			{
				Line++;
				Column = 1;
			}
			return ch;
		}

		public void Close()
		{
			this._reader.Close();
		}

	}
}
