//
// AUTOGENERATED 7/19/2009 5:56:59 PM
//
using System;

namespace Bamboo.Sql2
{
	public class SqlTokenType
	{
		public const int QUOTED_STRING = 0;
		public const int DATE = 1;
		public const int COMMA = 2;
		public const int SEMICOLON = 3;
		public const int EQUALS = 4;
		public const int NOT_EQUALS = 5;
		public const int LESS_THAN = 6;
		public const int LESS_THAN_OR_EQUAL = 7;
		public const int GREATER_THAN = 8;
		public const int GREATER_THAN_OR_EQUAL = 9;
		public const int LEFT_PAREN = 10;
		public const int RIGHT_PAREN = 11;
		public const int IDENTIFIER = 12;
		public const int AND = 13;
		public const int AS = 14;
		public const int ASC = 15;
		public const int NOT = 16;
		public const int DESC = 17;
		public const int DELETE = 18;
		public const int SET = 19;
		public const int SELECT = 20;
		public const int BETWEEN = 21;
		public const int BY = 22;
		public const int WHERE = 23;
		public const int LEFT = 24;
		public const int LIKE = 25;
		public const int FROM = 26;
		public const int REPLACE = 27;
		public const int RIGHT = 28;
		public const int ON = 29;
		public const int OR = 30;
		public const int ORDER = 31;
		public const int OUTER = 32;
		public const int GROUP = 33;
		public const int UNION = 34;
		public const int UPDATE = 35;
		public const int HAVING = 36;
		public const int VALUES = 37;
		public const int INNER = 38;
		public const int INSERT = 39;
		public const int INTO = 40;
		public const int JOIN = 41;
		public const int INTEGER = 42;
		public const int FLOAT = 43;

		public const int _ERROR_ = 44;
		public const int _EOF_ = 45;
	}
}
