//
// AUTOGENERATED 12/24/2008 11:44:09 AM
//
using System;

namespace Surf
{
	public class NodeType
	{
		// Nonterminals
		public const int Expression = 0;
		public const int ExpressionList = 1;
		public const int ExpressionListTail = 2;
		public const int ExpressionTail = 3;
		public const int Set = 4;
		public const int Tuple = 5;

		// Terminals
		public const int ASSIGNMENT = 6;
		public const int BITMAP = 7;
		public const int BOOLEAN = 8;
		public const int CHARACTER = 9;
		public const int COMMA = 10;
		public const int DIFFERENCE = 11;
		public const int EPSILON = 12;
		public const int EQUALS = 13;
		public const int FLOAT = 14;
		public const int IDENTIFIER = 15;
		public const int INTEGER = 16;
		public const int INTERSECTION = 17;
		public const int LEFT_CURLY_BRACE = 18;
		public const int LEFT_PAREN = 19;
		public const int RIGHT_CURLY_BRACE = 20;
		public const int RIGHT_PAREN = 21;
		public const int STRING = 22;
		public const int UNION = 23;

	}
}
