//
// AUTOGENERATED 12/24/2008 11:42:14 AM
//
using System;

namespace Surf
{
	public class TokenType
	{
		public const int STRING = 0;
		public const int INTERSECTION = 1;
		public const int CHARACTER = 2;
		public const int LEFT_PAREN = 3;
		public const int RIGHT_PAREN = 4;
		public const int COMMA = 5;
		public const int INTEGER = 6;
		public const int FLOAT = 7;
		public const int ASSIGNMENT = 8;
		public const int EQUALS = 9;
		public const int IDENTIFIER = 10;
		public const int BITMAP = 11;
		public const int DIFFERENCE = 12;
		public const int BOOLEAN = 13;
		public const int LEFT_CURLY_BRACE = 14;
		public const int UNION = 15;
		public const int RIGHT_CURLY_BRACE = 16;

		public const int _ERROR_ = 17;
		public const int _EOF_ = 18;
	}
}
