//
// AUTOGENERATED 1/21/2009 8:31:00 PM
//
using System;

namespace Bamboo.CSharp.Parser
{
	public class CSharpToken
	{
		public int Type;
		public string Value;

		public CSharpToken(int type)
		{
			Type = type;
			Value = null;
		}

		public CSharpToken(int type, string value)
		{
			Type = type;
			Value = value;
		}

	}
}
