//
// AUTOGENERATED 1/21/2009 8:31:00 PM
//
using System;

namespace Bamboo.CSharp.Parser
{
	public class CSharpTokenizer
	{
		private System.Text.StringBuilder _stringBuilder = new System.Text.StringBuilder();

		public CSharpTokenizer()
		{
		}

		public CSharpToken Tokenize(CSharpTextReader reader)
		{
			int n;
			char ch;

			_stringBuilder.Length = 0;

			//
			// Trim whitespace
			//
			while ((n = reader.Peek()) != -1)
			{
				ch = (char)n;
				switch (ch)
				{
					case ' ':
					case '\t':
					case '\r':
					case '\n':
						{
							reader.Read();
							break;
						}
					default:
						{
							goto s0;
						}
				}
			}

		s0:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '/':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s1;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s8;
					}
				case '{':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s11;
					}
				case '}':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s12;
					}
				case '(':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s13;
					}
				case ')':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case ',':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case ';':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s16;
					}
				case ':':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s17;
					}
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s18;
					}
				case '[':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s19;
					}
				case ']':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s20;
					}
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s21;
					}
				case '!':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s23;
					}
				case '<':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s25;
					}
				case '>':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s27;
					}
				case 't':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s29;
					}
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'f':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s34;
					}
				case '0':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s37;
					}
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s40;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s1:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '*':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s2;
					}
				case '/':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s5;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s2:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\t':
				case '\n':
				case '\r':
				case ' ':
				case '!':
				case '\"':
				case '#':
				case '$':
				case '%':
				case '&':
				case '\'':
				case '(':
				case ')':
				case '+':
				case ',':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case ';':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '[':
				case '\\':
				case ']':
				case '^':
				case '_':
				case '`':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '{':
				case '|':
				case '}':
				case '~':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s2;
					}
				case '*':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s3;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s3:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\t':
				case '\n':
				case '\r':
				case ' ':
				case '!':
				case '\"':
				case '#':
				case '$':
				case '%':
				case '&':
				case '\'':
				case '(':
				case ')':
				case '+':
				case ',':
				case '-':
				case '.':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case ';':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '[':
				case '\\':
				case ']':
				case '^':
				case '_':
				case '`':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '{':
				case '|':
				case '}':
				case '~':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s2;
					}
				case '*':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s3;
					}
				case '/':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s4;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s4:
			return new CSharpToken(CSharpTokenType.MULTILINECOMMENT, _stringBuilder.ToString());

		s5:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.COMMENT, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\t':
				case ' ':
				case '!':
				case '\"':
				case '#':
				case '$':
				case '%':
				case '&':
				case '\'':
				case '(':
				case ')':
				case '*':
				case '+':
				case ',':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case ';':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '[':
				case '\\':
				case ']':
				case '^':
				case '_':
				case '`':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '{':
				case '|':
				case '}':
				case '~':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s5;
					}
				case '\r':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s6;
					}
				case '\n':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s7;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.COMMENT, _stringBuilder.ToString());
					}
			}

		s6:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.COMMENT, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\n':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s7;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.COMMENT, _stringBuilder.ToString());
					}
			}

		s7:
			return new CSharpToken(CSharpTokenType.COMMENT, _stringBuilder.ToString());

		s8:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\t':
				case '\n':
				case '\r':
				case ' ':
				case '!':
				case '#':
				case '$':
				case '%':
				case '&':
				case '\'':
				case '(':
				case ')':
				case '*':
				case '+':
				case ',':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case ';':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '[':
				case ']':
				case '^':
				case '_':
				case '`':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '{':
				case '|':
				case '}':
				case '~':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s8;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s9;
					}
				case '\\':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s10;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s9:
			return new CSharpToken(CSharpTokenType.STRING, _stringBuilder.ToString());

		s10:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\t':
				case '\n':
				case '\r':
				case ' ':
				case '!':
				case '\"':
				case '#':
				case '$':
				case '%':
				case '&':
				case '\'':
				case '(':
				case ')':
				case '*':
				case '+':
				case ',':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
				case ';':
				case '<':
				case '=':
				case '>':
				case '?':
				case '@':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '[':
				case '\\':
				case ']':
				case '^':
				case '_':
				case '`':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
				case '{':
				case '|':
				case '}':
				case '~':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s8;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s11:
			return new CSharpToken(CSharpTokenType.LEFT_CURLY_BRACE, _stringBuilder.ToString());

		s12:
			return new CSharpToken(CSharpTokenType.RIGHT_CURLY_BRACE, _stringBuilder.ToString());

		s13:
			return new CSharpToken(CSharpTokenType.LEFT_PAREN, _stringBuilder.ToString());

		s14:
			return new CSharpToken(CSharpTokenType.RIGHT_PAREN, _stringBuilder.ToString());

		s15:
			return new CSharpToken(CSharpTokenType.COMMA, _stringBuilder.ToString());

		s16:
			return new CSharpToken(CSharpTokenType.SEMICOLON, _stringBuilder.ToString());

		s17:
			return new CSharpToken(CSharpTokenType.COLON, _stringBuilder.ToString());

		s18:
			return new CSharpToken(CSharpTokenType.PERIOD, _stringBuilder.ToString());

		s19:
			return new CSharpToken(CSharpTokenType.LEFT_BRACKET, _stringBuilder.ToString());

		s20:
			return new CSharpToken(CSharpTokenType.RIGHT_BRACKET, _stringBuilder.ToString());

		s21:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.EQUALS, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s22;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.EQUALS, _stringBuilder.ToString());
					}
			}

		s22:
			return new CSharpToken(CSharpTokenType.DOUBLEEQUALS, _stringBuilder.ToString());

		s23:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s24;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s24:
			return new CSharpToken(CSharpTokenType.NOTEQUALS, _stringBuilder.ToString());

		s25:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.LESSTHAN, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s26;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.LESSTHAN, _stringBuilder.ToString());
					}
			}

		s26:
			return new CSharpToken(CSharpTokenType.LESSTHANEQUALS, _stringBuilder.ToString());

		s27:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.GREATERTHAN, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '=':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s28;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.GREATERTHAN, _stringBuilder.ToString());
					}
			}

		s28:
			return new CSharpToken(CSharpTokenType.GREATERTHANEQUALS, _stringBuilder.ToString());

		s29:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'r':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s31;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s30:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s31:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'u':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s32;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s32:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'e':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s33;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s33:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.BOOLEAN, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.BOOLEAN, _stringBuilder.ToString());
					}
			}

		s34:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'a':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s35;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s35:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 'l':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s36;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s36:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case 's':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s32;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s37:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s38;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s38:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s39;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s39:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.FLOAT, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s39;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.FLOAT, _stringBuilder.ToString());
					}
			}

		s40:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new CSharpToken(CSharpTokenType._EOF_);
				}
				else
				{
					return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '_':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s30;
					}
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s38;
					}
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s40;
					}
				default:
					{
						return new CSharpToken(CSharpTokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		se:
			return new CSharpToken(CSharpTokenType._ERROR_, _stringBuilder.ToString());

		}

	}
}
