//
// AUTOGENERATED 1/1/2009 12:42:21 PM
//
using System;

namespace Ice
{
	public class NodeType
	{
		// Nonterminals
		public const int Expression = 0;
		public const int ExpressionList = 1;
		public const int Instruction = 2;
		public const int InstructionEnd = 3;
		public const int InstructionTail = 4;

		// Terminals
		public const int BOOLEAN = 5;
		public const int CHARACTER = 6;
		public const int COMMA = 7;
		public const int FLOAT = 8;
		public const int IDENTIFIER = 9;
		public const int INTEGER = 10;
		public const int NEWLINE = 11;
		public const int STRING = 12;

	}
}
