//
// AUTOGENERATED 1/1/2009 12:12:19 PM
//
using System;

namespace Ice
{
	public class TokenType
	{
		public const int NEWLINE = 0;
		public const int STRING = 1;
		public const int CHARACTER = 2;
		public const int COMMA = 3;
		public const int INTEGER = 4;
		public const int FLOAT = 5;
		public const int IDENTIFIER = 6;
		public const int BOOLEAN = 7;

		public const int _ERROR_ = 8;
		public const int _EOF_ = 9;
	}
}
