//
// AUTOGENERATED 1/1/2009 12:12:19 PM
//
using System;

namespace Ice
{
	public class Tokenizer
	{
		private System.Text.StringBuilder _stringBuilder = new System.Text.StringBuilder();

		public Tokenizer()
		{
		}

		public Token Tokenize(TextReader reader)
		{
			int n;
			char ch;

			_stringBuilder.Length = 0;

			//
			// Trim whitespace
			//
			while ((n = reader.Peek()) != -1)
			{
				ch = (char)n;
				switch (ch)
				{
					case ' ':
					case '\t':
						{
							reader.Read();
							break;
						}
					default:
						{
							goto s0;
						}
				}
			}

		s0:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\n':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s1;
					}
				case '\r':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s2;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s3;
					}
				case '\'':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s6;
					}
				case ',':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s9;
					}
				case '0':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s10;
					}
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s13;
					}
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'f':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s15;
					}
				case 't':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s20;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s1:
			return new Token(TokenType.NEWLINE, _stringBuilder.ToString());

		s2:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\n':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s1;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s3:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case ' ':
				case '.':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s4;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s4:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case ' ':
				case '.':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s4;
					}
				case '\"':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s5;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s5:
			return new Token(TokenType.STRING, _stringBuilder.ToString());

		s6:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case ' ':
				case '.':
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case '\\':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s7;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s7:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '\'':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s8;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s8:
			return new Token(TokenType.CHARACTER, _stringBuilder.ToString());

		s9:
			return new Token(TokenType.COMMA, _stringBuilder.ToString());

		s10:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.INTEGER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s11;
					}
				default:
					{
						return new Token(TokenType.INTEGER, _stringBuilder.ToString());
					}
			}

		s11:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType._ERROR_);
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s12;
					}
				default:
					{
						_stringBuilder.Append(ch);
						goto se;
					}
			}

		s12:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.FLOAT, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s12;
					}
				default:
					{
						return new Token(TokenType.FLOAT, _stringBuilder.ToString());
					}
			}

		s13:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.INTEGER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case '.':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s11;
					}
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s13;
					}
				default:
					{
						return new Token(TokenType.INTEGER, _stringBuilder.ToString());
					}
			}

		s14:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s15:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'a':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s16;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s16:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'l':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s17;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s17:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 's':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s18;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s18:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'e':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s19;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s19:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.BOOLEAN, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				default:
					{
						return new Token(TokenType.BOOLEAN, _stringBuilder.ToString());
					}
			}

		s20:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 's':
				case 't':
				case 'u':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'r':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s21;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		s21:
			n = reader.Peek();
			if (n == -1)
			{
				if (_stringBuilder.Length == 0)
				{
					return new Token(TokenType._EOF_);
				}
				else
				{
					return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
				}
			}
			ch = (char)n;
			switch (ch)
			{
				case 'A':
				case 'B':
				case 'C':
				case 'D':
				case 'E':
				case 'F':
				case 'G':
				case 'H':
				case 'I':
				case 'J':
				case 'K':
				case 'L':
				case 'M':
				case 'N':
				case 'O':
				case 'P':
				case 'Q':
				case 'R':
				case 'S':
				case 'T':
				case 'U':
				case 'V':
				case 'W':
				case 'X':
				case 'Y':
				case 'Z':
				case 'a':
				case 'b':
				case 'c':
				case 'd':
				case 'e':
				case 'f':
				case 'g':
				case 'h':
				case 'i':
				case 'j':
				case 'k':
				case 'l':
				case 'm':
				case 'n':
				case 'o':
				case 'p':
				case 'q':
				case 'r':
				case 's':
				case 't':
				case 'v':
				case 'w':
				case 'x':
				case 'y':
				case 'z':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s14;
					}
				case 'u':
					{
						reader.Read();
						_stringBuilder.Append(ch);
						goto s18;
					}
				default:
					{
						return new Token(TokenType.IDENTIFIER, _stringBuilder.ToString());
					}
			}

		se:
			return new Token(TokenType._ERROR_, _stringBuilder.ToString());

		}

	}
}
