//
// AUTOGENERATED 7/17/2009 5:09:41 PM
//
using System;

namespace Bamboo.Csv2
{
	public class CsvNodeType
	{
		// Nonterminals
		public const int Cell = 0;
		public const int CellList = 1;
		public const int CellListTail = 2;
		public const int Row = 3;
		public const int RowEnd = 4;

		// Terminals
		public const int BOOLEAN = 5;
		public const int COMMA = 6;
		public const int EOF = 7;
		public const int EPSILON = 8;
		public const int FLOAT = 9;
		public const int INTEGER = 10;
		public const int NEWLINE = 11;
		public const int QUOTED_STRING = 12;
		public const int STRING = 13;

	}
}
