//
// AUTOGENERATED 7/17/2009 5:09:41 PM
//
using System;

namespace Bamboo.Csv2
{
	public class CsvTokenType
	{
		public const int STRING = 0;
		public const int QUOTED_STRING = 1;
		public const int COMMA = 2;
		public const int NEWLINE = 3;
		public const int BOOLEAN = 4;
		public const int INTEGER = 5;
		public const int FLOAT = 6;

		public const int _ERROR_ = 7;
		public const int _EOF_ = 8;
	}
}
