//
// AUTOGENERATED 7/17/2009 5:09:41 PM
//
using System;

namespace Bamboo.Csv2
{
	public class CsvToken
	{
		public int Type;
		public string Value;

		public CsvToken(int type)
		{
			Type = type;
			Value = null;
		}

		public CsvToken(int type, string value)
		{
			Type = type;
			Value = value;
		}

	}
}
